name: CI/CD for Spring Boot

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set Docker Image Tag
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          echo "DOCKER_IMAGE_TAG=${VERSION}" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:$DOCKER_IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:$DOCKER_IMAGE_TAG

      - name: Create docker-compose.yml from secret
        run: echo "${{ secrets.DOCKER_COMPOSE_YML }}" > docker-compose.yml

      - name: Create application.yml from secret
        run: echo "${{ secrets.APPLICATION_YML }}" > application.yml

      - name: Create .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy config files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: |
            docker-compose.yml
            application.yml
            .env
          target: /home/ubuntu/

      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            export IMAGE_TAG=${{ env.DOCKER_IMAGE_TAG }}
            echo "Deploying version: $IMAGE_TAG"
            cd /home/ubuntu
            docker-compose pull
            docker-compose down || true
            docker-compose up -d
            echo "Deployment complete."
